services:
  emsi-ebank-discovery-service:
    build: ./discovery-service
    container_name: emsi-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
  emsi-ebank-config-service:
    build: ./config-service
    container_name: emsi-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      emsi-ebank-discovery-service:
        condition: service_healthy
